### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by renerpdev** [jugglinmike/selenium-chromedriver#3]
**Error: connect ETIMEDOUT 172.217.8.112:80**
    _at Object.exports._errnoException (util.js:1023:11)
    at exports._exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)_
npm WARN EBUSY: resource busy or locked, rmdir 'C:\Users\myuser\AppData\Roaming\npm\node_modules\selenium-chromedriver'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "selenium-chromedriver"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

**npm ERR! selenium-chromedriver@0.0.2 install: `node install`**
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the selenium-chromedriver@0.0.2 install script 'node install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the selenium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs selenium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls selenium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rene.ricardo\npm-debug.log

**Comment by renerpdev** [comment]
Why i got this isssue?

**Comment by jugglinmike** [comment]
I can't say for sure, and I unfortunately don't have the bandwidth to help troubleshoot. Note that this module has been deprecated for almost 3 years--from the project's `README.md` file:

> ## Deprecation Notice
> 
> This project has been deprecated and will no longer be maintained. Please see the ChromeDriver project ([project source](https://github.com/giggio/node-chromedriver), [npm module](https://www.npmjs.com/package/chromedriver)) for equivalent functionality.

I'd recommend switching to that module rather than investing time fixing problems with this one.
